### ISSUE TITLE
Environment variables may be bug

### ISSUE THREAD

**Issue by Tomorrowxxy** [jina-ai/discoart#154]
I tried to define DISCOART_DEFAULT_PARAMETERS_YAML in the custom file myflow.yml, he is not effective

```
jtype: Flow
with:
  protocol: http
  monitoring: true
  cors: true
  port: 51001
  port_monitoring: 51002  # prometheus monitoring port
  env:
    ...

    DISCOART_DEFAULT_PARAMETERS_YAML: /opt/project/disco/default.yml
    DISCOART_DEFAULT_PARAMETERS_YAML: '/opt/project/disco/default.yml'
    DISCOART_DEFAULT_PARAMETERS_YAML: './default.yml'
    DISCOART_DEFAULT_PARAMETERS_YAML: ./default.yml

    `↑ None of them are valid`
    ...

```

Is there a mistake in the way I write? Or is it written in the wrong place?
How should I write it? Thank you!
