### ISSUE TITLE
bug: replica = 1 doesnt work?

### ISSUE THREAD

**Issue by brokeDude2901** [jina-ai/discoart#167]
It seem discoart doesn't respect replica = 1 settings in .yml file:
```
jtype: Flow
with:
  protocol: http
  monitoring: false
  cors: true
  port: 51001
  port_monitoring: 51002  # prometheus monitoring port
  env:
    JINA_LOG_LEVEL: debug
    DISCOART_DISABLE_IPYTHON: 1
    DISCOART_DISABLE_RESULT_SUMMARY: 1
    WANDB_MODE: disabled
executors:
  - name: discoart
    uses: DiscoArtExecutor
    replicas: 1  # change this if you have larger VRAM
    floating: false  # new feature in Jina 3.7, set this to true allows `create` to be immediately returned without waiting the response on the client
  - name: poller
    uses: ResultPoller
```
