### ISSUE TITLE
Large Memory Usage During Diffusion

### ISSUE THREAD

**Issue by jwelch1324** [jina-ai/discoart#90]
During a diffusion with the following parameters I am getting what I think is a very high memory usage (though maybe not? I am honestly not sure)

Diffusion parameters 
```json
{
    "text_prompts": ["a magical realism painting of a rainbow colored kiwi bird surrounded by fractal mist, standing on a forest floor:3.5","forest:1.2","4k resolution, cinematic lighting:3.5"],
    "init_image": null,
    "width_height": [1536, 768],
    "skip_steps": 10,
    "steps": 1000,
    "cut_ic_pow": 1,
    "init_scale": 1000,
    "clip_guidance_scale": 80000,
    "tv_scale": 0,
    "range_scale": 150,
    "sat_scale": 0,
    "cutn_batches": 4,
    "diffusion_model": "512x512_diffusion_uncond_finetune_008100",
    "use_secondary_model": true,
    "diffusion_sampling_mode": "ddim",
    "perlin_init": false,
    "perlin_mode": "mixed",
    "seed": 3012672161,
    "eta": 0.8,
    "clamp_grad": true,
    "clamp_max": 0.05,
    "randomize_class": true,
    "clip_denoised": false,
    "fuzzy_prompt": false,
    "rand_mag": 0.05,
    "cut_overview": "[12]*400+[4]*600",
    "cut_innercut": "[4]*400+[12]*600",
    "cut_icgray_p": "[0.2]*400+[0]*600",
    "display_rate": 10,
    "n_batches": 1,
    "batch_size": 1,
    "batch_name": "kiwi_test",
    "clip_models": ["ViT-B-32::openai","ViT-B-16::openai","RN50x4::openai"],
    "name_docarray": "test"
}
```
Output of htop 
![image](https://user-images.githubusercontent.com/4706333/181126393-2705f6e4-81a0-417b-8271-d1d777732078.png)

my flow yaml (only change is floating=true) 
```yaml
jtype: Flow
with:
  protocol: http
  monitoring: true
  cors: true
  port: 51001
  port_monitoring: 51002  # prometheus monitoring port
  env:
    JINA_LOG_LEVEL: debug
    DISCOART_DISABLE_IPYTHON: 1
    DISCOART_DISABLE_RESULT_SUMMARY: 1
executors:
  - name: discoart
    uses: DiscoArtExecutor
    env:
      CUDA_VISIBLE_DEVICES: RR0:2  # change this if you have multiple GPU
    replicas: 1  # change this if you have larger VRAM
    floating: true  # new feature in Jina 3.7, set this to true allows `create` to be immediately returned without waiting the response on the client
  - name: poller
    uses: ResultPoller
```

System Specs
```
OS: Ubuntu Server 20.04
 -- Linux 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Memory: 32GB
GPU: NVidia RTX Titan - 24GB
```

The memory usage does appear to increase as the session progresses -- here is the output from htop at iteration 660/1000 
![image](https://user-images.githubusercontent.com/4706333/181127100-d21b50ce-4aea-4afd-a9fb-f95ee1d631c4.png)

It is hard to tell if this is a memory leak, or if it is simply the in memory cache of the docArray growing as more frames are rendered?
